# Default values for golink
tailscale:
  # Auth key for Tailscale authentication
  # Get from: https://login.tailscale.com/admin/settings/keys
  # Recommended: Use tagged key with no expiration
  authKey: ""

deployment:
  replicaCount: 1
  
  image:
    repository: ghcr.io/tailscale/golink
    tag: main
    pullPolicy: IfNotPresent

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

persistence:
  enabled: true
  size: "1Gi"
  storageClass: "local-path"

namespace:
  create: true
  name: "golink"