apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golink-data
  namespace: golink
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
