apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "golink.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "golink.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "golink.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        {{- if .Values.tailscale.authKey }}
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-auth
              key: TS_AUTHKEY
        {{- end }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /home/nonroot
          readOnly: false
        {{- end }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- if .Values.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-data
      {{- end }}