{{- if .Values.tailscale.authKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-auth
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "golink.labels" . | nindent 4 }}
type: Opaque
stringData:
  TS_AUTHKEY: {{ .Values.tailscale.authKey | quote }}
{{- end }}